# setup

In [1]:
import torch
import matplotlib.pyplot as plt
import os

In [2]:
if os.getcwd().split('/')[-1] == 'notebooks':
    os.chdir('..')

from data.load_data import LoadData
# from configs.gate import LoadDataConfig
# from configs.baseline import LoadDataConfig
from configs.fake import LoadDataConfig
from utils import get_inputs

# init

In [3]:
loader_config = LoadDataConfig()

In [4]:
dataloader = LoadData(**loader_config.__dict__)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

--> WARNING: USING RANDOM FAKE DATA!!


# data

In [5]:
train_dl = dataloader.get_train_dataloader()
val_dl = dataloader.get_val_dataloader()
test_dl = dataloader.get_test_dataloader()

In [6]:
train_dl.dataset_size, val_dl.dataset_size, test_dl.dataset_size

(4, 2, 2)

In [7]:
for train_batch in (train_dl):
    raw, exam_id, label = train_batch
    ecg = get_inputs(raw).to(device)
    label = label.to(device).float()
    break

In [8]:
raw.shape, raw

(torch.Size([2, 4096, 12]),
 tensor([[[-3.4788, -1.8564,  1.6224,  ..., -0.2184,  2.4258,  1.8915],
          [-3.4632, -1.8798,  1.5834,  ..., -0.2106,  2.4414,  1.9110],
          [-3.4515, -1.8330,  1.6185,  ..., -0.2301,  2.4258,  1.8993],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]],
 
         [[ 0.0700, -0.0500, -0.1200,  ..., -0.0600, -0.0650, -0.0450],
          [ 0.0650, -0.0500, -0.1150,  ..., -0.0650, -0.0700, -0.0500],
          [ 0.0750, -0.0600, -0.1350,  ..., -0.0700, -0.0700, -0.0500],
          ...,
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000]]]))

In [9]:
ecg.shape, ecg

(torch.Size([2, 12, 2560]),
 tensor([[[-2.9172, -2.9094, -2.8977,  ..., -0.9555, -0.9594, -0.9633],
          [-1.5873, -1.5444, -1.5795,  ..., -0.6591, -0.6630, -0.6864],
          [ 1.3299,  1.3650,  1.3182,  ...,  0.2964,  0.2964,  0.2769],
          ...,
          [-1.4742, -1.4937, -1.4859,  ..., -2.7963, -2.7963, -2.8002],
          [ 1.8096,  1.7862,  1.7979,  ...,  0.7839,  0.7878,  0.7878],
          [ 1.4430,  1.4235,  1.4391,  ...,  0.4134,  0.4212,  0.4212]],
 
         [[ 0.0250,  0.0250,  0.0050,  ...,  0.0000,  0.0000,  0.0000],
          [-0.0050, -0.0050, -0.0050,  ...,  0.0000,  0.0000,  0.0000],
          [-0.0300, -0.0300, -0.0100,  ...,  0.0000,  0.0000,  0.0000],
          ...,
          [ 0.0350,  0.0350,  0.0350,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0000,  0.0000,  0.0150,  ...,  0.0000,  0.0000,  0.0000],
          [ 0.0050,  0.0100,  0.0050,  ...,  0.0000,  0.0000,  0.0000]]],
        device='cuda:0'))

In [10]:
exam_id.shape, exam_id

((2,), array([ 247003, 2678117], dtype=int32))

In [11]:
label.shape, label

(torch.Size([2, 6]),
 tensor([[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]], device='cuda:0'))